version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: My-Complex-Pwd-123

    container_name: liquibase-demo-db
    ports:
      - "1433:1433"
    networks:
      - my-network

networks:
  my-network:
    name: liquibase-demo-network

